blank_issues_enabled: true
contact_links:
  - name: ğŸ—’ï¸  pcapML README
    url: https://github.com/nprint/pcapML#readme
    about: Consult the pcapML README first.
  - name: ğŸ“– pcapML Usage Information
    url: https://nprint.github.io/pcapml_walk.html
    about: Learn more about how to use pcapML here.
  - name: ğŸ“– pypcapML Usage Information
    url: https://nprint.github.io/pypcapml_walk.html
    about: Learn more about how to use pypcapML here.
